#Mendefinisikan versi dari docker compose yaitu versi 3.7
version: '3.7'

services:
  item-app:
    #Menggunakan docker image dari docker hub
    image: hubrizqi/item-app:v1

    #Melakukan port mapping agar dapat diakses dari port 80 di host
    ports:
      - "80:8080"

    #Menentukan service item-app membutuhkan item-db untuk berjalan
    depends_on:
      - item-db
    
    #Perintah agar container selalu restart ketika terhenti
    restart: always

  item-db:
    #Menggunakan docker image mongo dengan tag 3 dari docker hub
    image: mongo:3

    #Menggunakan volume docker app-db dan menghubungkannya ke path /data/db
    volumes:
      - app-db:/data/db

    #Perintah agar container selalu restart ketika terhenti
    restart: always

volumes:
  #Membuat volume docker dengan nama app-db
  app-db: